"""new tiles_designsuitable tales

Revision ID: 26ecf1fe3f83
Revises: 74ad66544fca
Create Date: 2025-03-06 12:56:07.989875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ecf1fe3f83'
down_revision: Union[str, None] = '74ad66544fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suitable_places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_suitable_places_id'), 'suitable_places', ['id'], unique=False)
    op.create_table('collection_suitable_places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['tile_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['suitable_places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_suitable_places_collection_id'), 'collection_suitable_places', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_suitable_places_id'), 'collection_suitable_places', ['id'], unique=False)
    op.create_index(op.f('ix_collection_suitable_places_place_id'), 'collection_suitable_places', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_suitable_places_place_id'), table_name='collection_suitable_places')
    op.drop_index(op.f('ix_collection_suitable_places_id'), table_name='collection_suitable_places')
    op.drop_index(op.f('ix_collection_suitable_places_collection_id'), table_name='collection_suitable_places')
    op.drop_table('collection_suitable_places')
    op.drop_index(op.f('ix_suitable_places_id'), table_name='suitable_places')
    op.drop_table('suitable_places')
    # ### end Alembic commands ###
