"""collection name dupliction false

Revision ID: 49ea45eb6129
Revises: e90aac2487bb
Create Date: 2025-03-06 18:46:14.579572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ea45eb6129'
down_revision: Union[str, None] = 'e90aac2487bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tile_collections_name_key', 'tile_collections', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tile_collections_name_key', 'tile_collections', ['name'])
    # ### end Alembic commands ###
