"""new tiles_design tables with changes

Revision ID: 74ad66544fca
Revises: 
Create Date: 2025-03-05 00:55:54.463612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ad66544fca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tile_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('finish_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='collectionstatus'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tile_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finish_id'], ['tile_finishes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['tile_materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['tile_series.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['size_id'], ['tile_sizes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tile_collections_category_id'), 'tile_collections', ['category_id'], unique=False)
    op.create_index(op.f('ix_tile_collections_finish_id'), 'tile_collections', ['finish_id'], unique=False)
    op.create_index(op.f('ix_tile_collections_id'), 'tile_collections', ['id'], unique=False)
    op.create_index(op.f('ix_tile_collections_material_id'), 'tile_collections', ['material_id'], unique=False)
    op.create_index(op.f('ix_tile_collections_seller_id'), 'tile_collections', ['seller_id'], unique=False)
    op.create_index(op.f('ix_tile_collections_series_id'), 'tile_collections', ['series_id'], unique=False)
    op.create_index(op.f('ix_tile_collections_size_id'), 'tile_collections', ['size_id'], unique=False)
    op.create_table('tile_designs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tile_name', sa.String(length=255), nullable=False),
    sa.Column('tile_code', sa.String(length=20), nullable=False),
    sa.Column('color_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['tile_colors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('tile_code')
    )
    op.create_index(op.f('ix_tile_designs_id'), 'tile_designs', ['id'], unique=False)
    op.create_table('favorite_tiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('tile_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_tiles_id'), 'favorite_tiles', ['id'], unique=False)
    op.create_foreign_key(None, 'favorite_collections', 'tile_collections', ['collection_id'], ['id'], ondelete='CASCADE')
    op.add_column('tile_categories', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('tile_colors', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('tile_finishes', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('tile_materials', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('tile_series', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('tile_sizes', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('tiles', sa.Column('tile_design_id', sa.UUID(), nullable=True))
    op.drop_constraint('tiles_tile_code_key', 'tiles', type_='unique')
    op.create_index(op.f('ix_tiles_collection_id'), 'tiles', ['collection_id'], unique=False)
    op.create_index(op.f('ix_tiles_tile_design_id'), 'tiles', ['tile_design_id'], unique=False)
    op.drop_constraint('tiles_color_id_fkey', 'tiles', type_='foreignkey')
    op.create_foreign_key(None, 'tiles', 'tile_collections', ['collection_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tiles', 'tile_designs', ['tile_design_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tiles', 'name')
    op.drop_column('tiles', 'tile_code')
    op.drop_column('tiles', 'color_id')
    op.drop_column('tiles', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiles', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('tiles', sa.Column('color_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('tiles', sa.Column('tile_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('tiles', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tiles', type_='foreignkey')
    op.drop_constraint(None, 'tiles', type_='foreignkey')
    op.create_foreign_key('tiles_color_id_fkey', 'tiles', 'tile_colors', ['color_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_tiles_tile_design_id'), table_name='tiles')
    op.drop_index(op.f('ix_tiles_collection_id'), table_name='tiles')
    op.create_unique_constraint('tiles_tile_code_key', 'tiles', ['tile_code'])
    op.drop_column('tiles', 'tile_design_id')
    op.drop_column('tile_sizes', 'created_at')
    op.drop_column('tile_series', 'created_at')
    op.drop_column('tile_materials', 'created_at')
    op.drop_column('tile_finishes', 'created_at')
    op.drop_column('tile_colors', 'created_at')
    op.drop_column('tile_categories', 'created_at')
    op.drop_constraint(None, 'favorite_collections', type_='foreignkey')
    op.drop_index(op.f('ix_favorite_tiles_id'), table_name='favorite_tiles')
    op.drop_table('favorite_tiles')
    op.drop_index(op.f('ix_tile_designs_id'), table_name='tile_designs')
    op.drop_table('tile_designs')
    op.drop_index(op.f('ix_tile_collections_size_id'), table_name='tile_collections')
    op.drop_index(op.f('ix_tile_collections_series_id'), table_name='tile_collections')
    op.drop_index(op.f('ix_tile_collections_seller_id'), table_name='tile_collections')
    op.drop_index(op.f('ix_tile_collections_material_id'), table_name='tile_collections')
    op.drop_index(op.f('ix_tile_collections_id'), table_name='tile_collections')
    op.drop_index(op.f('ix_tile_collections_finish_id'), table_name='tile_collections')
    op.drop_index(op.f('ix_tile_collections_category_id'), table_name='tile_collections')
    op.drop_table('tile_collections')
    # ### end Alembic commands ###
