"""Added AI Tile Processing Models

Revision ID: 98e7c895b2f9
Revises: a15b644c810e
Create Date: 2025-03-16 11:54:44.387104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e7c895b2f9'
down_revision: Union[str, None] = 'a15b644c810e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_segmentations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_image_url', sa.String(length=500), nullable=False),
    sa.Column('wall_mask_url', sa.String(length=500), nullable=False),
    sa.Column('floor_mask_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_segmentations_id'), 'room_segmentations', ['id'], unique=False)
    op.create_table('matching_tiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tile_id', sa.UUID(), nullable=False),
    sa.Column('recommended_tile_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['recommended_tile_id'], ['tiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_tiles_id'), 'matching_tiles', ['id'], unique=False)
    op.create_table('processed_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segmentation_id', sa.UUID(), nullable=False),
    sa.Column('applied_tiles_data', sa.String(), nullable=False),
    sa.Column('processed_image_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['segmentation_id'], ['room_segmentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_images_id'), 'processed_images', ['id'], unique=False)
    op.create_table('tile_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('segmentation_id', sa.UUID(), nullable=False),
    sa.Column('layout_1_url', sa.String(length=500), nullable=False),
    sa.Column('layout_2_url', sa.String(length=500), nullable=True),
    sa.Column('layout_3_url', sa.String(length=500), nullable=True),
    sa.Column('layout_4_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['segmentation_id'], ['room_segmentations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tile_comparisons_id'), 'tile_comparisons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tile_comparisons_id'), table_name='tile_comparisons')
    op.drop_table('tile_comparisons')
    op.drop_index(op.f('ix_processed_images_id'), table_name='processed_images')
    op.drop_table('processed_images')
    op.drop_index(op.f('ix_matching_tiles_id'), table_name='matching_tiles')
    op.drop_table('matching_tiles')
    op.drop_index(op.f('ix_room_segmentations_id'), table_name='room_segmentations')
    op.drop_table('room_segmentations')
    # ### end Alembic commands ###
