"""Added paint wall AI with env file updated

Revision ID: 9a9fa7896b8f
Revises: e355cfffced5
Create Date: 2025-03-16 19:41:26.619435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9fa7896b8f'
down_revision: Union[str, None] = 'e355cfffced5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('painted_walls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segmentation_id', sa.UUID(), nullable=False),
    sa.Column('paint_color', sa.String(length=7), nullable=False),
    sa.Column('painted_image_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['segmentation_id'], ['room_segmentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_painted_walls_id'), 'painted_walls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_painted_walls_id'), table_name='painted_walls')
    op.drop_table('painted_walls')
    # ### end Alembic commands ###
