"""collection name duplictiontrue

Revision ID: a15b644c810e
Revises: 49ea45eb6129
Create Date: 2025-03-06 23:57:47.956467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15b644c810e'
down_revision: Union[str, None] = '49ea45eb6129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tile_designs', 'tile_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('tile_designs_tile_code_key', 'tile_designs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tile_designs_tile_code_key', 'tile_designs', ['tile_code'])
    op.alter_column('tile_designs', 'tile_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
