"""all doen with suitable placess

Revision ID: e90aac2487bb
Revises: 26ecf1fe3f83
Create Date: 2025-03-06 13:14:56.971480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90aac2487bb'
down_revision: Union[str, None] = '26ecf1fe3f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suitable_places', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suitable_places', 'deleted_at')
    # ### end Alembic commands ###
